### ISSUE TITLE
Displaying Message via Kodi JSON with an Action

### ISSUE THREAD

**Issue by CinemaVision** [CinemaVision/script.cinemavision#120]
[Thread](https://cinemavision.tv/forums/topic/1077-pop-up-text-on-the-screen-isn%C2%B4t-visible-in-cinemavision-action/)

**Comment by ruuk** [comment]
I wonder if he's tried it during a movie while CV is playing, not just during a movie in general. Some skin integration could be hiding notifications while CV is playing. I don't see any reason why it wouldn't work as he has it.

**Comment by ruuk** [comment]
Closing as duplicate of #121
