### ISSUE TITLE
iTunes Trailer is picking up 'Clips'

### ISSUE THREAD

**Issue by frankiej45nz** [CinemaVision/script.cinemavision#73]
It seems that the iTunes feeds are now returning both trailers and movie clips. The scraper appears to not differentiate, and given the 'clip' is often first, plays that rather than the 'trailer'.

I seemed to fix this by adding an extra check into the get_trailers function of the itunes scraper.py

Added at 127:

`if clip['title'] == 'Trailer':`

**Comment by CinemaVision** [comment]
Exclude from being scraped into the CV database as well as ignored for trailer processing.

**Comment by CinemaVision** [comment]
Verified.
