### ISSUE TITLE
Invalid Characters in File Names

### ISSUE THREAD

**Issue by CinemaVision** [CinemaVision/script.cinemavision#84]
[https://cinemavision.tv/forums/topic/1022-trivia-crash-due-to-invalid-characters-in-file-names/](https://cinemavision.tv/forums/topic/1022-trivia-crash-due-to-invalid-characters-in-file-names/)

**Comment by ruuk** [comment]
Should be fixed in version 1.0.14

**Comment by CinemaVision** [comment]
Confirmed.
